### ISSUE TITLE
Uncaught ReferenceError: ace is not defined 

### ISSUE THREAD

**Issue by tigerclaw-az** [hlashbrooke/Code-Snippet-Library#4]
After installing the Code Snippet Library plugin I noticed that there was no editor showing when creating a new snippet. Looking at the console I got the error "Uncaught ReferenceError: ace is not defined"

**Comment by tigerclaw-az** [comment]
This is fixed. Turns out I needed to change the link for loading the 'ace' library within the `load_ace()` function from `http:` to `https:`

**Comment by ekatzenstein** [comment]
Just to be clear, this is not fixed. You haven't submitted a PR to fix it. A pending PR is here: https://github.com/hlashbrooke/Code-Snippet-Library/pull/8/files
